### PR TITLE
Suggested refinements to the "simplified" branch

### PR DESCRIPTION
**Pull request by deanwampler**
I like the changes a lot. I added some logic to make it easier to switch between implementation options using command-line options, except for the Java KafkaModelServer, where it proved difficult due to the need to declare a few variables `final` (the `streams` and `restService` objects).

### CODE REVIEW

**Comment by deanwampler** [comment]
I also removed some directory trees that were "left behind".

**Comment by deanwampler** [comment]
Are you referring to how I punted on command-line arguments in the Java Kafka server? I tried following the same pattern I used in the Java Akka server, where I initialize mutable variables, then override based on command-line arguments, but the closure at the end, 

```java
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            try {
                streams.close();
                restService.stop();
            } catch (Exception e) {
...
```

caused compiler complains if `streams` and `restService` aren't final. I'm willing to try a different approach.

**Comment by blublinsky** [comment]
Lets merge this one and try experiment more

**Comment by deanwampler** [comment]
Okay. Done.

**Pull request merged**
